### ISSUE TITLE
Страница решения задания

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#100]

**Comment by webwayer** [comment]
@VintorezVS 
> Как будет выглядеть область для решения задач (если хотя бы для программирования, то это надо среду запилить...)? Я думаю надо просто, что бы пользователь загрузил файлы решения задачи (что угодно код, текст, картинки).

@webwayer
> Да, среду пилить - явно не наш вариант.

@alexeychikk 
> Можно решения прекреплять в виде файлов, если там что-то объемное или если по другому не получится дать ответ. А если ответ короткий, но содержит код, то поддержку синтаксиса я думаю не сложно впаять, уверен готовые скрипты уже есть.

@webwayer
+1 про подсветку и файлы
