### ISSUE TITLE
Основные страницы

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#107]
Мне кажется надо так: 3 основных страницы
1) Новости - то что произошло (что-то с заданиями пользователя) или с тем за чем следим
2) Рабочая страница - как на ФБ, там есть все что бы работать (добавлять, проверять, решать...)
3) Страница профиля - как главная в ВК например - информация о себе, и сборная статистика о себе

Другие люди видят только страницу профиля, остальное личное.
как вам?

**Comment by webwayer** [comment]
тут на гитхабе например - 2 страницы (рабочая + профиль) и новости
На фб - тоже 2 (рабочая + новости) и профиль
На ВК - тоже 2 (рабочая + профиль) и новости

Но нам ИМХО нужно либо все 3, либо один из вариантов выше
Но смешивать рабочую и профиль - ИМХО не наш вариант.

**Comment by VintorezVS** [comment]
В общем я согласен. Только одно хочу уточнить. Как будет выглядеть область для решения задач (если хотя бы для программирования, то это надо среду запилить...)? Я думаю надо просто, что бы пользователь загрузил файлы решения задачи (что угодно код, текст, картинки).

**Comment by webwayer** [comment]
Да, среду пилить - явно не наш вариант.
Я тут еще твиттер поколупал, там вообще Лента новостей и Уведомления - разные страницы

**Comment by alexeychikk** [comment]
Можно решения прекреплять в виде файлов, если там что-то объемное или если по другому не получится дать ответ. А если ответ короткий, но содержит код, то поддержку синтаксиса я думаю не сложно впаять, уверен готовые скрипты уже есть.

**Comment by webwayer** [comment]
+1 про подсветку и файлы

**Comment by webwayer** [comment]
Только это обсуждение вообще не сюда

**Comment by webwayer** [comment]
При чем походу Новости и Уведомления - это разные вещи
