### ISSUE TITLE
Правки прототипа (УИ) Срочно, для демонстрации в Понедельник

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#119]
"Навыки" - "Умею"
"Цели" - "Хочу"
Под каждой задачей даже в коротком виде - показать скилы задачи.
Убрать никнейм из под аватара.
В профиле "Умею" и "Хочу" - под аватар.
Под аватаром: Имя, експа, сколько "умею" и "хочу", что "умею" и что "хочу", задачи (в таком порядке)

В списке всех пользователей:
Для каждого сразу показывать "умею" и "хочу" (справа)
При клике - открывать его профиль

"навыки" в меню - "Дерево умений"
"Моя страница" в меню - "Главная"

добавить в меню "Рамки компетенций":
Список (как в задачах)
Компетенция1...Компетенция Н

**Comment by alexeychikk** [comment]
Как ты себе представляешь, если все будет под аватаром? А что тогда не под аватаром будет? А если у пользователя 20 скиллов и 20 целей, тоже все под аватар? Что значит задачи под аватар?
Про рамки компетенций вообще не понял.

**Comment by webwayer** [comment]
У нас сейчас под автаром:
Имя
Никнейм
Експа
Сколько и каких задач решено, создано, проверено...
Сколько "Умею" и "Хочу" есть у пользователя

Надо так:
Имя
Экспа
Сколько "Умею" и "Хочу" есть у пользователя
Список этих хочу и умею
Сколько и каких задач решено, создано, проверено...

**Comment by webwayer** [comment]
По рамкам
Просто добавь в меню новый пункт, "Компетенции"
А в нем просто список, такой же как в задачах, но только из одного заголовка "Компетенция 1","Компетенция 2"..."Компетенция N"

**Comment by alexeychikk** [comment]
Порядок еще можно поменять, но под профилем писать названия задач и скиллов... Хорошо, давай я сделаю так как вы придумали, заскриню, мы посмеемся, а потом вы придумаете что-то получше.

**Comment by alexeychikk** [comment]
Тот еще прикол:
> Для каждого сразу показывать "умею" и "хочу" (справа)

> При клике - открывать его профиль

При клике куда? На имя пользователя? Если да, то кнопка expand вообще не нужна.

**Comment by webwayer** [comment]
Кнопка - действительно не нужна. Думаю было-бы неплохо что бы при клике на всю плитку.

Названия задач писать не надо.
Надо названия "умею" и "хочу"
По задумке они не должны быть большими.

Можно даже ширину колонок поменять

**Comment by webwayer** [comment]
Отличная работа закрываю.
