### ISSUE TITLE
Не работает показ дерева скилов

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#120]

**Comment by alexeychikk** [comment]
jquery в зависимости проекта забыл прописать.

**Comment by webwayer** [comment]
Обязательно надо Jquery?
Есть JqueryLite как angular.element

А вообще DOM из контроллера - плохая практика, надо через Директиву.

**Comment by alexeychikk** [comment]
Мне не для DOM, а для поиска элемента в массиве. Это первое что мне выдал Гугл, значит, наверное, самое продуктивное.

**Comment by webwayer** [comment]
Посмотри lo-dash
