### ISSUE TITLE
Изменить стиль вкладок на странице отображения одного задания

### ISSUE THREAD

**Issue by VintorezVS** [webwayer/skills#140]
![2015-02-10 19 34 05](https://cloud.githubusercontent.com/assets/9587463/6132601/2e739aac-b15c-11e4-9c42-076654a348eb.png)
Заменить цвета на такие как в рисунке ниже:
![csdcsdc](https://cloud.githubusercontent.com/assets/9587463/6132703/0ea3942e-b15d-11e4-8b05-92a6f915a994.png)

**Comment by reverse603** [comment]
Беру.
