### ISSUE TITLE
Заменить стиль ссылок

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#141]
Заменить стиль для ссылок (тег \<a\>), а именно: убрать подчеркивание, изменить цвет и сделать чтобы он менялся при наведении на более светлый.

**Comment by opalenko** [comment]
Беру

**Comment by opalenko** [comment]
Изменить цвет на какой? 
В каком файле нужно изменить стиль ссылок?

**Comment by VintorezVS** [comment]
Они должны быть такого же цвета как обычный текст (rgba(0,0,0,0.87)), при наведении цвет должен меняться на rgba(0,0,0,0.54). Заменить нужно стиль всех ссылок, кроме тех, что в используются в верхней панели (для них прописаны отдельные классы).
