### ISSUE TITLE
Добавить количества заданий во вкладки на главной

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#152]
Сделать чтобы на первой картинке было как на второй.
![11](https://cloud.githubusercontent.com/assets/10129207/6194877/42664ba0-b3d1-11e4-8551-76de428e78ca.png)
![12](https://cloud.githubusercontent.com/assets/10129207/6194878/444b7f94-b3d1-11e4-8ed7-921b5063eb6c.png)
Для выполнения понадобятся самые базовые знания angular.js

**Comment by Preissinger** [comment]
беру))
