### ISSUE TITLE
Страница просмотра всех скиллов

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#32]
Закрепляю за собой создание веб-страницы "Просмотр всех Skills" и реализация функциональной части (Angular.js).
[все Skills загружаются из файла JSON]

ОПИСАНИЕ СТРАНИЦЫ:
1] 4 обязательных кнопки для всех страниц [вверху страницы] (профиль пользователя, все пользователи, скилы (вот этот файл), все задания;

2] ТАБЛИЦА = дерево всех Skills, разбитая на колонки:
- № Skill
- 1-ая группа Skills (основные Skills)
- 2-ая группа Skills (второстепенные Skills, которые пренадлежат каждому из ОСНОВНЫХ Skills)
- 3-я группа Skills (Skills, которые пренадлежат к второстепенным Skills)
p.s.: Skills второй и третьей группы могут повторятся в разных группах: второстепенные могут повторятся в основной группе, а 3-я группа может повторяться во второстепенных Skills.

3] ОКНА ФИЛЬТРА (перед таблицей Skills): возможность поиска по группе необходимого Skill = три окна поиска по 3-м группам Skills с возможностью выбора. Кнопка "ФИЛЬТРОВАТЬ" = запускает фильтрацию, и выводит на экран именно ту информацию, которая нам необходима.

*** у кого есть еще какие-то пожелания к этой странице = прошу писать их сюда: с удовольствием готов обсудить Ваши пожелания с Родионом.

**Comment by ma1405** [comment]
По какому признаку разбивать скилы на группы и под-группы?

**Comment by VintorezVS** [comment]
@ma1405, я думаю, по глубине в дереве. Если конечно я тебя правильно понял...

**Comment by ma1405** [comment]
Да я думаю - как мне скилы из JSON вытащить так, что-бы они вроде-как включали друг друга.
Графический интерфейс я продумал - что-то, типа этого:
![2015-01-01 23 57 56](https://cloud.githubusercontent.com/assets/10208004/5593379/5e3f32f0-9212-11e4-84b9-0329860782e4.png)

**Comment by webwayer** [comment]
@ma1405 Уже все и есть так как ты говоришь, свойства "parents" - у скиллов, это как раз ИД над скиллов текущеко скилла.

**Comment by VintorezVS** [comment]
@ma1405, cкилы надо отображать в виде дерева. И что бы оно масштабируемым, то есть можно было двигаться по нему (выше-ниже) и видеть больше узлов (скилов) или меньше.

**Comment by webwayer** [comment]
Пока что - хотя бы просто дерево, все и сразу

**Comment by ma1405** [comment]
Думаю, что теперь, когда уже есть просмотр "Всех скилов" - можно его и разбить по группам?

**Comment by webwayer** [comment]
Не можно, а нужно
