### ISSUE TITLE
Главное меню

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#33]
На страницу index.html должны быть 4 общие кнопки, которые будут показываться для всех страниц.

**Comment by VintorezVS** [comment]
@webwayer, мы не можем добавлять лэйблы в твоем репозитории. Возможно в настройках это можно поправить, а может и нет...

**Comment by ma1405** [comment]
та-же самая ситуация... =(

**Comment by ma1405** [comment]
Серега подал ХОРОШУЮ идею. Хочу использовать его набросок, и реализовать main_page именно вот так:
![main_page](https://cloud.githubusercontent.com/assets/10208004/5593245/83017862-920a-11e4-89db-2d3e33220f59.png)

**Comment by ma1405** [comment]
Серега нарисовал отличный макет СТРАНИЦЫ ЗАДАЧ. Хочу использовать его идею для написания main_page:
![main_page](https://cloud.githubusercontent.com/assets/10208004/5593332/31b2a2ac-920e-11e4-91a0-5aaaec438226.png)

**Comment by webwayer** [comment]
ок, лейблы пока что добавлю сам, а там посмотрим.

**Comment by webwayer** [comment]
По макетам - пробуйте/делайте , это же ваш проект :-)

**Comment by ma1405** [comment]
...на странице "главного меню" предлагаю, справа: выводить Skills и Needs по запросу одноименных кнопок.

**Comment by webwayer** [comment]
@ma1405
А как там сейчас происходит?

**Comment by ma1405** [comment]
Сейчас там я тупо прописал все статически (для примера)...

**Comment by webwayer** [comment]
Главное меню это не страница. Это главное меню. Зачем там кнопки, проще сразу выводить одни над другими.

**Comment by ma1405** [comment]
Хочу сделать вывод СКИЛОВ и НИДСОВ в виде дерева...

**Comment by webwayer** [comment]
Сделай. В сайдбаре слева?

**Comment by ma1405** [comment]
да (слева)... постараюсь реализовать...

**Comment by ma1405** [comment]
Хочу сделать кнопки "ГЛАВНОГО МЕНЮ" нажатыми, если открыта одноименная страница.

**Comment by webwayer** [comment]
Так есть иссуе по поводу нормального "Главного меню"
