### ISSUE TITLE
Страница отображения всех задач

### ISSUE THREAD

**Issue by VintorezVS** [webwayer/skills#35]
Закрепляю за собой [Сергей VintorezVS Чернышенко] создание страницы для отображения
всех задач проекта .
Создал прототип страницы:
![skillsprototype](https://cloud.githubusercontent.com/assets/9587463/5592658/cfe597d4-91e3-11e4-841e-28397eb13b54.png)
Обсуждаем, дополняем, критикуем...
P. S. Программа называется [Balsamiq Mockups](http://balsamiq.com/)

**Comment by ma1405** [comment]
Эта програ помогает рисовать макеты проектов?...

**Comment by VintorezVS** [comment]
@ma1405, там примитивы. Просто набросать по быстрому общее расположение, чтобы в общем иметь представление, что где будет (без дизайна, как будто карандашом накидал).

**Comment by ma1405** [comment]
полезно, реально экономит кучу времени (буду использовать)... спасибо...

**Comment by VintorezVS** [comment]
@ma1405, есть и другие похожие, но я не стал пробовать, скачал одну... Нет за что, используй.

**Comment by webwayer** [comment]
Я обычно сразу в html прототипирую :-)

**Comment by webwayer** [comment]
ок, делай :white_check_mark:

**Comment by VintorezVS** [comment]
Переделываю эту страницу под Material Design.

**Comment by VintorezVS** [comment]
Сделано
