### ISSUE TITLE
АДМИНКА: форма для присваивания Skills - суб-Skills

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#37]
Предлагаю разарботать форму для присваивания каждому основному Skill (на пример: JavaSkript, Java, Ruby...) - суб-скилы (ООП, Логическое программирование, Функциональное программирование...). А суб-скилам = суб-суб-скилы... и т.д.
(...и куда-то это все записывать. Пока - не знаю куда)

**Comment by VintorezVS** [comment]
Вообщем, форму для добавления скила в общее дерево. Но я думаю рано пока про админку, так как пока что у нас о правах пользователя и регистрации речь не идет и мы можем напрямую редактировать файл JSON.

**Comment by ma1405** [comment]
Точняк. Вот только как его реализовать так, что-бы старшие скилы включали в себя младшие? Это мне надо для формы вывода всех скилов (пока-что могу только вывести их общим списком).

**Comment by webwayer** [comment]
@VintorezVS ты прав, пока оно совсем не надо. :-)
@ma1405 Уже все и есть так как ты говоришь, свойства "parents" - у скиллов, это как раз ИД над скиллов текущеко скилла.
