### ISSUE TITLE
Мне кажется, что скиллы, нужные для выполнения - это неправильно

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#38]
Мне кажется, что __*скиллы, нужные для выполнения*__ - это неправильно. Потому что это и есть те скиллы, которые пользователь получит при выполнении данной задачи. Выполнением задачи ты доказываешь, что у тебя есть такой скилл, который ты хочешь добавить в свое резюме на сайте.

**Comment by alexeychikk** [comment]
>alexeychikk
...[И вообще, мне кажется, что скиллы, нужные для выполнения - это неправильно. Потому что это и есть те скиллы, которые пользователь получит при выполнении данной задачи.]...

Это не так... скилы, нужные для выполнения - это то, чем ты уже владеешь для того, что-бы выполнить данное задание. Ну, к примеру - если ты хочешь решить уравнение: (1 + 2), и получить скилл "суммирование цифр", то тебе, как минимум - необходимо знать, что такое цифры... И за решение этого уравнения ты получишь свой needs ("суммировавание").

**Comment by alexeychikk** [comment]
Если чел действительно владеет скиллом ООП и хочет подтвердить его выполнением какого-то задания, которое даст этот скилл, то неужели ему сначала нужно будет подниматься по цепочке задач, которые дают более мелкие скиллы, составляющие этот большой скилл ООП, вплоть от понятия класса. Я думаю, что __*скиллы, нужные для выполнения*__ актуальны только тогда, когда это не просто задача, а какой-то __важный проект__, скорее всего __оплачиваемый__.

**Comment by alexeychikk** [comment]
@ma1405 ответил:

>Давай представим, что мы нифига не гребемся в программировании... и вот мы - новички, которые хотят получить Skill "JavaScript". Но что учить и как это сделать - не шарим... У нас есть какой-то набор скилов:
умеем считать
умеем писать
понимаем русский и украинский язык
все!
Мы задаем этот скилл ("JavaScript") = нам выпадает МИЛЛИОН ЗАДАЧ... и какую из этих задач мы с тобой начнем развязывать?
Я так думаю, после первой СУПЕР-СЛОЖНОЙ задачи, которую ты выбрал на угад (первую попавшуюся), которая тебе покажется через пару недель пустяком, но сейчас кажется чем-то невероятным - заставит тебя УЙТИ с платформы!
Короче = набор "Нужных для выполнения Скилов" нужен только для фильтрации: что-бы выбрасывались именно те задачи, которые ты можешь сейчас решить. Задача со сложным уровнем не выпадет тебе до тех пор, пока ты не решишь задачу по-проще.
Если-же ты уже владеешь ООП - никакой проффесионал не захочет проходить по-новой изучению этой безумно "интерестной" темы. =) Я так понимаю - что, чел говорит нам при регистрации свои СКИЛЫ, и мы даем ему задание, которое позволяет сразу-же ему подтвердить этот скил: в таком случае ему нужно решить только 1 задачу, а не 100 (но - подтверждать все-равно надо... ну или придумать какой-то другой механизм. К примеру с минусами експы, если другие пользователи выразили свое сомнение по поводу его знаний в разработке задач на ту или иную тему...).
Выходит, что платформа и ПОДТВЕРЖДАЕТ ТВОИ ЗНАНИЯ (которые уже есть), и ПОМОГАЕТ ОБУЧАТЬСЯ === аудитория пользователей значительно БОЛЬШЕ!

**Comment by alexeychikk** [comment]
@ma1405 

>Короче = набор "Нужных для выполнения Скилов" нужен только для фильтрации:

В этом контексте __*нужные для выполнения скиллы*__ - это те, которые у тебя сейчас есть. Значит, если ты новичок и скиллов у тебя нет, то и задачи никакие ты решить не сможешь. Ведь чтобы решить, как ты говоришь, задачу на суммирование, нужно __знать, как суммировать числа__, не достаточно просто знать, что такое числа.
Как представляю себе ситуацию я. Когда приходит новичок, который ничего не знает, наш сайт предлагает ему выбрать направление ("Программирование", например) или профессию (C# Junior Developer, for example) - которые по сути тоже являются скиллами, только абстрактными. Строится дерево скиллов, которые необходимы для получения этих абстрактных скиллов. Если у тебя нет никаких скиллов, то тебе будут предлагаться самые простые задачи, которые дадут тебе скиллы-листья в нашем дереве. Естественно, что тебе понадобится прочитать какую-нибудь литературу или пройти какие-нибудь уроки/курсы, для получения теоретических знаний, которые понадобятся для решения задачи.
Но если ты не новичок, то ты можешь прокрутить дерево скиллов повыше и выбрать себе скилл покруче - сайт посоветует тебе другие задачи, более сложные. Все просто.

**Comment by alexeychikk** [comment]
@ma1405 ответил:

> @alexeychikk 
Ты спрашивал: "Зачем указывать в задачах НЕОБХОДИМЫЕ СКИЛЫ ДЛЯ ЕЁ РЕШЕНИЯ?" Я правильно тебя понял?
Для того, что бы сайт выбрасывал пользователю ЗАДАЧИ, которые соответсвуют его знаниям... (конечно, ему придется самостоятельно подняться на 1 ступеньку, изучив теоретический материал... но - 1 ступенька легче, чем 10-20 одновременно).
Вроде как мы нашли ответ на этот вопрос? или ты имеешь ввиду, что-бы пользователь сам регулировал, что ему изучать (какие скилы подтверждать, не зависимо от того, есть у него для этого способности, указанные в его существующих скилах или нет)?

**Comment by alexeychikk** [comment]
@ma1405 
Смотри. Допустим у тебя есть скиллы "Полиморфизм" и "Наследование". А ты хочешь получить скилл "ООП". Но помимо того, что у тебя уже есть в скиллах, "ООП" так же состоит из скилла "Инкапсуляция". А на серваке лежит __задача__, которая даст тебе скилл "Инкапсуляция", __в которой никаким образом не указано, какие скиллы необходимы для ее выполнения__. Наш сайт видит, что тебе не хватает скилла "Инкапсуляция" - вот он и бросит тебе эту задачу, потому что она дает недостающий скилл.

**Comment by alexeychikk** [comment]
@ma1405 ответил:

>@alexeychikk 
согласен... что-бы получить skill "ООП" = необходимо набрать багаж определенных обязательных скилов (полиморфизм, наследование, инкапсуляция).

**Comment by webwayer** [comment]
Если по делу - то верно, скиллы которые нужны для решения задачи - можно убрать, и в функционале мы не потеряем. Но придется принят за аксиому что за одну задачу можно получить скилл только на один уровень выше твоих. Таким образом скиллы которые нужны - автоматически можно вывести (все подскиллы тех скиллов которые получит пользователь) И получим что чаще всего задача будет создавать на 1 какой-то скилл.

**Comment by VintorezVS** [comment]
Я все таки думаю надо сделать так:
* задача может реализовывать любое количество любых скилов;
* для доступа к решению задачи юзер должен иметь все подскилы тех скилов которые реализует задача;
* задача будет рекомендоваться юзеру исходя из его Нидсов, а также опираясь на его Скилс и выбранный маршрут в дереве;
* начинающий юзер, после выбора направления (пока что у нас только программирование), должен будет в обязательном порядке доказать, что владеет базовыми навыками в этой области (для этого выполнит пак задач, типа "Основы программирования"; что в него будет входить - отдельная дискуссия), после чего получит базовые скилы и сможет продвигаться дальше;
* для людей которые не хотят постепенно проходить цепочку решения задач можно реализовать систему доната (заплати и получи доступ к одной задаче из уровня 4 (к примеру); заплати больше получи доступ к одной любой задаче; еще больше - 3 задачи... потом 3 задачи по цене 2 и т. д.)
           Почему именно так? Для начинающих программистов правильней будет такая ступенчатая система получения скилов (от легкого к тяжелому). А на счет "залетных" профи... Во-первых, пока сайт не популярен (среди работодателей) он таким людям будет бесполезным. Во-вторых если сайт наберет такую популярность и станет таким людям полезным, то они не пожалеют заплатить за ускоренный курс. В остальных случаях я думаю каждому будет полезно пройти и повторить давно знакомые вещи (тем более, тот кто знает материал, выполнит все намного быстрее).
           И еще, я думаю задачи могут быть и настолько объемные, что могут реализовывать целые поддеревья скилов (решая которые, можно будет двигаться быстрее).

**Comment by VintorezVS** [comment]
Я думаю надо сделать так:
* задачи могут реализовывать любое количество любых скилов;
* чтобы получить доступ к решению задачи, нужно иметь все подскилы тех скилов, что реализует задача;
* задачи будут рекомендоваться юзеру исходя из его скилов и нидсов (то есть рекомендованными станут задачи ближайшие к скилам которые уже есть и которые лежат на пути к заветным нидсам);
* начинающий юзер должен после выбора области деятельности (пока только программирование), должен будет выполнить пак задач, который будет открыт для начинающих (типа "Основы программирования"), чем подтвердит свои базовые знания и сможет двигаться дальше;
* для тех кто не хочет постепенно проходить по дереву можно ввести систему доната (задачи можно будет открывать за деньги, а так же за внутреннюю валюту, которую тоже скорее всего можно будет купить за реал).
Я думаю тут главное это целевая аудитория, и я не думаю, что мы будет ориентироваться (особенно первое время) на продвинутых программистов. Ведь изначально цель стояла в обучении студентов, и для них такая ступенчатая структура будет полезнее. Ну и возможность покупки доступа к некоторым задачам за внутреннюю валюту разнообразит этот процесс.

**Comment by VintorezVS** [comment]
Я думаю надо сделать так:

задачи могут реализовывать любое количество любых скилов;
чтобы получить доступ к решению задачи, нужно иметь все подскилы тех скилов, что реализует задача;
задачи будут рекомендоваться юзеру исходя из его скилов и нидсов (то есть рекомендованными станут задачи ближайшие к скилам которые уже есть и которые лежат на пути к заветным нидсам);
начинающий юзер должен после выбора области деятельности (пока только программирование), должен будет выполнить пак задач, который будет открыт для начинающих (типа "Основы программирования"), чем подтвердит свои базовые знания и сможет двигаться дальше;
для тех кто не хочет постепенно проходить по дереву можно ввести систему доната (задачи можно будет открывать за деньги, а так же за внутреннюю валюту, которую тоже скорее всего можно будет купить за реал).
Я думаю тут главное это целевая аудитория, и я не думаю, что мы будет ориентироваться (особенно первое время) на продвинутых программистов. Ведь изначально цель стояла в обучении студентов, и для них такая ступенчатая структура будет полезнее. Ну и возможность покупки доступа к некоторым задачам за внутреннюю валюту разнообразит этот процесс.

**Comment by VintorezVS** [comment]
Я думаю надо сделать так:

* задачи могут реализовывать любое количество любых скилов;
* чтобы получить доступ к решению задачи, нужно иметь все подскилы тех скилов, что реализует задача;
* задачи будут рекомендоваться юзеру исходя из его скилов и нидсов (то есть рекомендованными станут задачи ближайшие к скилам которые уже есть и которые лежат на пути к заветным нидсам);
начинающий юзер должен после выбора области деятельности (пока только программирование), должен будет выполнить пак задач, который будет открыт для начинающих (типа "Основы программирования"), чем подтвердит свои базовые знания и сможет двигаться дальше;
* для тех кто не хочет постепенно проходить по дереву можно ввести систему доната (задачи можно будет открывать за деньги, а так же за внутреннюю валюту, которую тоже скорее всего можно будет купить за реал).
Я думаю тут главное это целевая аудитория, и я не думаю, что мы будет ориентироваться (особенно первое время) на продвинутых программистов. Ведь изначально цель стояла в обучении студентов, и для них такая ступенчатая структура будет полезнее. Ну и возможность покупки доступа к некоторым задачам за внутреннюю валюту разнообразит этот процесс.

**Comment by webwayer** [comment]
@VintorezVS
"задачи могут реализовывать любое количество любых скилов" и "чтобы получить доступ к решению задачи, нужно иметь все подскилы тех скилов, что реализует задача" - тут есть парадокс, а если пользователь должен будет получить при выполнении два скила, которые один над другим в дереве - то получим что за решении задачи ты получишь тот скилл который нужен что бы ее решить. впрочем это легко обходиться, мы в "нужные скиллы" никогда не добавляем те скиллы которые ты получишь, и все будет ок.
Хотя все равно если скиллы которые нужны реализует задача будут под-скллами других скиллов которые реализует эта-же задача - то тут странная штука будет.
Так что предлагаю запретить это, что бы можно было выбрать только те скиллы (для задачи) которые не есть потомками друг-друга.

**Comment by webwayer** [comment]
"после выбора области деятельности" и "нидс" ИМХО - одно и то же.
Пак задач - это просто пак задач, его может создать любой, и с любым названием, в этом и смысл, мы то можем добавить такой как "Основы программирования" для начинающих, но будут они его решать как "пак" или по отдельности из списка рекомендованных - не важно.

**Comment by webwayer** [comment]
"для тех кто не хочет постепенно проходить по дереву можно ввести систему доната" - Это всмысле?
Донат вообще штука плохая, особенно при набивке аудтории, и особенно при набивке ее студентами)
Да и вариантов других нет, как можно обучиться чему-то не проходя по дереву скиллов постепенно? оО
Я думаю прогресс ограничивать не стоит.

**Comment by alexeychikk** [comment]
@webwayer 
> Хотя все равно если скиллы которые нужны реализует задача будут под-скллами других скиллов которые реализует эта-же задача - то тут странная штука будет.

ШТА?!

**Comment by webwayer** [comment]
Есть задача, есть 2 скила которые она даёт, и один из них предок другого. Получается что нижний и иерархии скилл - и нужен для выполнения задачи, и даеться после выполнения.
