### ISSUE TITLE
Предложение что что-бы получить скилл, нужно решить не 1 задачу на этот скилл, а например 3, или 5. Т.е. что бы разнообразные попались, и лучше усвоилось.

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#40]

**Comment by VintorezVS** [comment]
Нормально. Повторение - мать учения. Добавим скилам свойство, которое будет показывать, сколько нужно выполнить задач (которые дают такой скил), а у пользователя будет показываться прогресс возле скила в дереве.
