### ISSUE TITLE
Шаблон "Вывод всех пользователей"

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#44]
Хочу сделать шаблон "Вывод всех пользователей", который будет отражаться по нажатию на кнопку "Все пользователи" (из файла show.html) в шаблоне "Главное меню".

**Comment by webwayer** [comment]
насколько я помню show.html - это шаблончик страницы вывода одного пользователя.
Опять же, страница это а не "шаблон" если есть что-то кроме ХТМЛ.
Откуда данные будут браться?
И главное меню - это главное меню, а не "шаблон", шаблон - это ХТМЛ файл, а кнопки можно нажать не в файле, а "в главном меню" :-)

ПС: я много-много поправляю, но это не от того что я злой, тут такая штука - что думаешь, то и говоришь. и если формулировка странная - то возможно не так что-то думается.
ППС: да и читать и понимать это в правильной формулировке легче :-)

**Comment by ma1405** [comment]
Можно поменять файл show.html на show_all_users.html, и записывать туда всех пользователей. Или в каком формате лучше всего хранить всех пользователей? и где?...

**Comment by webwayer** [comment]
Файл шоу.хтмл отвечает за показ одного пользователя. Он тут вообще не при чем. В хтмл - только шаблон, пользователей надо хранить в БД, пока это у нас папка моделс.
