### ISSUE TITLE
Шаблон "Просмотр одного пользователя"

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#45]
Хочу реализовать ШАБЛОН, который будет отражать информацию об 1 пользователе, при выборе его из списка "Все пользователи".
Данные будут подгружаться из projects_list.json.

**Comment by webwayer** [comment]
если данные будут подгружаться - это не сколько шаблон сколько уже страница, (шаблон это только ХТМЛ)
Что это вообще за файл такой (Список проектов) и как он связан с информацией о пользователях?
"при выборе его из списка "Все пользователи" - можно не писать, и так понятно, но кроме этого на страницу можно будет попасть и другими путями.

**Comment by VintorezVS** [comment]
Да и на странице пользователя должна быть инфа которая сейчас находится в /front/users/1.json. То есть скилы, нидсы, проекты, личная инфа и резюме (не все это правда есть в том файле, это нужно добавить).

**Comment by ma1405** [comment]
добавить - это не проблема: могу доделать это и "ручками" (пока-что все-равно нету формы регистрации)...

**Comment by webwayer** [comment]
Ручками не надо, надо автоматически. Регистрации пока нету, но пользователей можно добавлять ручками прямо в файлы.
