### ISSUE TITLE
Нужно заменить "job" (задание) в названиях страниц, на что-то другое

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#48]
Я без намерения оскорбить чьи-то знания английского, но каким макаром "задача" переводится как "job"? Изначально у нас были проекты, поэтому и сделали "projects_list.json". А вообще рекомендую переименовать на "task".

**Comment by webwayer** [comment]
Мне не нравиться "project"
Есть у кого то ещё предложения помимо jobs и task?

**Comment by ma1405** [comment]
- вариант а) = mission;
- вариант b) = exercise;
- но, по моему = лучше всего звучит >>> вариант с) = target.

**Comment by alexeychikk** [comment]
Все за "task"? Ну тогда единогласно) /play trololo

**Comment by VintorezVS** [comment]
task

**Comment by alexeychikk** [comment]
## __Job vs. Task; What's the Difference?__

__Job__: Is a single work assignment or operation that employees perform as part of their occupations; a specific duty, role, or function.
__Task__: Is a single and separate activity that clearly advances a work assignment and is a logical portion of that assignment. It is an assigned piece of work often to be finished within a certain time.

## __Job vs. Task; В чем разница?__

__Job__: Является одиночным рабочим распоряжением (операцией), которое (которую) сотрудники выполняют в рамках своих должностей; конкретная обязанность, роль или функция.
__Task__: Является одиночным и отдельным видом деятельности, который несомненно продвигает рабочее задание и является логической частью этого задания. Это назначаемая часть работы, которая часто должна быть завершена в течение определенного времени.

**Comment by VintorezVS** [comment]
монетка уже все решила...
