### ISSUE TITLE
Нужно убрать "Ответ" из подтверждения задания (approve)

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#49]
В текстовом поле написано:

>  "...здесь находится ОТВЕТ и РЕШЕНИЕ ЗАДАНИЯ, который помогает проверяющему в быстрой проверке задания..."

Во-первых, ОТВЕТ и РЕШЕНИЕ ЗАДАНИЯ - это одно и то же. Если нет, то тогда подразумевается, что сервер будет хранить ответы, что совсем не требуется, по скольку задания проверяют пользователи. 
Во-вторых, это текстовое поле неуместно, по скольку новые задания придумывают сами пользователи, а те, кто проверяют не должны иметь доступ к ответам. Какой тогда смысл им проверять? Тем более, что они смогут скопировать себе решение и проверять на правильность выполняющих это задание. При чем, как мы уже однажды обсуждали, пользователи могут забрасывать задания, решение которых пока что не существует, что особенно выгодно для нас.

**Comment by VintorezVS** [comment]
Согласен. ОТВЕТ и РЕШЕНИЕ ЗАДАНИЯ не одно и тоже, как я понимаю Саша подразумевал, что ОТВЕТ - это написаное автором задания правильное решение, но это бред (Леша уже написал почему).

**Comment by alexeychikk** [comment]
Из проверки задания (check) ответ тоже нужно убрать.

**Comment by VintorezVS** [comment]
И еще, по-моему, в создании задания тоже было.

**Comment by webwayer** [comment]
Ответ, или похожее поле - может содержать не совсем ответ, а то что по мнению автора задачи должен сделать решающий, что бы проверяющим было легче и лучше проверять (им же решать ее заново не нужно, да и долго и неефективно)

**Comment by VintorezVS** [comment]
@webwayer, а что поля "Условие задания" недостаточно? По-моему в нем и описывается, что решающий должен сделать, а точнее там должны описываться условия, которым должно отвечать решение, проблему которую оно должно решать и какие оно должно реализовывать функции.

**Comment by webwayer** [comment]
Это для решающего, а подсказка для проверяющего - тоже крутая штука, например если мне надо проверить задачу - то было бы круто что бы я видел решение предложеное автором задачи, тогда все намного проще. И исключаться моменты неправильного понимания условий задачи проверяющим. Я - за такую штуку. (если не пойдет - уберем)

**Comment by VintorezVS** [comment]
Вообщем какой-то комментарий для проверяющего. Возможно с картинками.

**Comment by webwayer** [comment]
по хорошему (на будущее) надо добавить возможность добавлять к любым текстовым данных - мультимедийные файлы. как в ВК
