### ISSUE TITLE
Нормальная навигационная панель

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#51]
Хочется запилить нормальную навигационную панель, похожую на гитхабовскую, да знаний не хватает, но кое что уже получается. Как вам такой вариант?
![2015-01-07 20 48 17](https://cloud.githubusercontent.com/assets/10129207/5651362/7b10d1e4-96af-11e4-9dc7-b6db194cb5cd.png)

**Comment by VintorezVS** [comment]
Норм. Хорошо было бы если бы каждый хотя бы нарисовал в общих чертах как он видит сайт. Потом из всех предложений можно было бы выбрать лучший или слепить из нескольких идей одну.

**Comment by webwayer** [comment]
Идея с панелью - круто, мне нравиться. Развивай идею.

**Comment by ma1405** [comment]
Хочу сделать кнопки "ГЛАВНОГО МЕНЮ" нажатыми, если открыта одноименная страница.

**Comment by VintorezVS** [comment]
Сделано
