### ISSUE TITLE
Нашел библиотеки для визуализации ГРАФА (не Дракулы)

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#52]
* http://arborjs.org/ - простая, но довольно неплохо настраиваемая.
* http://sigmajs.org/ - самая популярная, говорят, что мощная, рендерить можно не только в canvas, но и в WebGL.

Я больше склоняюсь ко второму варианту. Если сообщество не против, могу взяться за изучение и, надеюсь, в течении уже нескольких дней, наши скиллы будут визуализированы по-человечески.

**Comment by VVPol** [comment]
творите :)

**Comment by webwayer** [comment]
Однозначно второй :-)
Мне очень нравиться, только надо будет обернуть это все с Директиву Angular.js

**Comment by alexeychikk** [comment]
@webwayer, да что-то такое видел, только пока что не смог разобраться, поэтому поначалу сделал тупо через контроллер.

**Comment by webwayer** [comment]
В контроллерах - нельзя напрямую обращаться к DOM. это все в директивах (кастомных тегах)

**Comment by alexeychikk** [comment]
Зато можно напрямую обратиться к id элемента страницы и создать с помощью него экземпляр sigma.

**Comment by webwayer** [comment]
Это и есть обратиться к DOM напрямую. ты же по ID - получаешь сырой DOM обьект.

**Comment by alexeychikk** [comment]
@webwayer 
Короче, я из контроллера делал так и работало:

```javascript
 s = new sigma({
            graph: g,
            container: 'graph-container', //А вот и наш ID элемента
            settings: { labelColor: 'node' }
         });
```

Но не суть, ведь я все уже обернул в директиву. Ща пулл реквест пошлю.

**Comment by webwayer** [comment]
@alexeychikk оно то работать будет, но концептуально не совсем верно.
Директива - ок, понравилась.
