### ISSUE TITLE
Новая структура скилов

### ISSUE THREAD

**Issue by VintorezVS** [webwayer/skills#54]
Я так понимаю достаточно просто добавить свойство каждому скилу, является ли тот листком.

**Comment by webwayer** [comment]
даже не так, добавлять свойство можно только листкам, а остальным - не добавлять вообще, так наглядней что-ли :-)

**Comment by VintorezVS** [comment]
@webwayer, по-моему, лучше пускай у всех скилов будет одинаковая сигнатура.

**Comment by webwayer** [comment]
@VintorezVS, она и одинаковая, чему равно несуществующее свойство? undefined (что приводиться к false)

**Comment by alexeychikk** [comment]
@VintorezVS, мсье знает толк в js.

**Comment by VintorezVS** [comment]
Ну тогда в значении свойства нет толку вообще.

**Comment by alexeychikk** [comment]
Есть, если ты напишешь if (skills[id].isLeaf) { ... } тебе вернет false и условие не выполнится, даже если свойство не определено.

**Comment by alexeychikk** [comment]
Кстати, визуализируя граф, я уже понял, что скиллу нужно свойство children, которое хранит массив ссылок на детей узла. Это свойство так же необходимо, чтобы просчитать все скиллы-листья от указанного родителя, что нам в дальнейшем понадобится

**Comment by webwayer** [comment]
JSON - сырые данные, там только необходимое, это же почти БД, никакого дублирования данных.
Нужно написать функцию которая принимает эти данные, и выдает обьект в котором как раз и есть какие угодно дополнительные свойства (которые выводятся из базовых).
Я бы даже еще рекомендовал добавить свойства all_parents (все родители аж до корня) и all_children (все дети аж до листьев) и свойства leafs и all_leafs.

**Comment by VVPol** [comment]
народ где у вас описана структура листиков? имхо у вас не хватает пару свойств... ;) бо есть бомбезная идея, но я ее смогу выдать только после просмотра стуктуры...

**Comment by VintorezVS** [comment]
@VVPol, path /models/skills.json. Тут описана структура скилов, на днях появится еще свойство у каждого (является ли он листком).
