### ISSUE TITLE
"Моя страница"

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#60]
...предлагаю первые 2 таблицы (Skills и Needs) подтягивать с файла users.json

**Comment by webwayer** [comment]
А чем отличается страница "профайл" - от того что в левом сайдбаре?

**Comment by ma1405** [comment]
...в принципе - ничем, если брать только первые две таблицы (Skills и Needs)... ну а так-то профайл от левого сайд-бара отличается тем, что в профайле есть еще работа с ЗАДАНИЯМИ...
[сам, пока-еще, не определился - надо СКИЛЫ и НИДСЫ выводить в "профейле" или нет...]

**Comment by webwayer** [comment]
@ma1405  
> выходит: просто, тупо, дублируются данные и все... а пользы от этого никакой

Да, мне тоже так кажется.
А еще хорошо бы наверно сделать эту страницу главной.

**Comment by ma1405** [comment]
Ок... сделаю...
