### ISSUE TITLE
Создание ЗАДАНИЯ (task)

### ISSUE THREAD

**Issue by ma1405** [webwayer/skills#61]
Если всех устраивает функционал формы СОЗДАНИЕ ЗАДАНИЯ [форма "моя страница" >>> кнопка "создать новое задание"] >>> хочу реализовать эту форму с записью новых ЗАДАНИЙ в json.

**Comment by webwayer** [comment]
динамики пока не надо, в начале 1 этапа - запустим БД, в файлы писать - беда будет :-)

**Comment by ma1405** [comment]
То-есть - пока-что с этой страничкой ждем основательной реализации версии №0?...
Кстати - а есть какие-то рамки версии №0? (чтоб понемать, на каком этапе мы переходим к реализации 1ой версии)

**Comment by webwayer** [comment]
Смотри список задач, все что помечены "stage 0" должны быть выполены.
А вообще - этап 0 (прототип) - когда будут основные страницы, но их нельзя менять через интерфейс. т.е. статика, но вся основная.
