### ISSUE TITLE
Как будем добавлять ачивки?

### ISSUE THREAD

**Issue by alexeychikk** [webwayer/skills#64]
Допустим у нас есть ачивка C# Basics, для получения которой нужны скиллы "Структура программы на C#", "Типы данных в C#" и "Основы ООП". Сейчас, для ее внедрения в нашу псевдоБД "skills.json", нужно для каждого из указанных скиллов в свойство parents добавить ID ачивки. Так и будем добавлять их или создадим отдельный файл achievments, в котором для каждой ачивки будет свойство children с id-шниками необходимых для ее достижения скиллов?
И еще одно, для ачивки parent-ом будет root графа или какой-нибудь отдельный узел, типо achievments, а может у самых крутых ачивок, типо "C# SeniorDeveloper levelOver9000op_gg_easy" вообще не будет parent-а?

**Comment by VintorezVS** [comment]
Рarent-a не будет только у "Абсолютные знания". У остального должны быть. Добавление так как ты в начале сказал походу будет.
