### ISSUE TITLE
Каталогизировать свалку в front

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#66]

**Comment by ma1405** [comment]
какие каталоги ты хочешь видеть?...

**Comment by webwayer** [comment]
Ваши варианты

**Comment by ma1405** [comment]
ПРЕДЛОЖЕНИЕ №1:
>> Каталог "job":
- job_approve.html
- job_check.html
- job_create.html
- job_decision.html
- job_viewer_all.html
- job_viewer_one.html
>> Каталог "profile":
- profile.html
- profile_viewer_all.html
>> Каталог "skills":
- skills.html
>> Этот каталог = /front (файлы без изменений):
- app.js
- index.html
- style.css
>> Этот каталог = /front (изменения):
- main.html + User/show.html = думаю, можно удалить...
- User/controllers.js = можно вынпести в эту папку
- папка User/ = тоже можно удалить, когда она окажется пустой

**Comment by webwayer** [comment]
воу, ну и форматирование :-)

**Comment by ma1405** [comment]
чуток подкорректировал... =)

**Comment by webwayer** [comment]
кнопочка Preview есть)

**Comment by ma1405** [comment]
ок... ) (спасибо... теперь буду знать)

**Comment by webwayer** [comment]
в папке job (например) - можно не писать job в имени всех файлов. (и так аналогично для всех)
ПС: лучше назвать его "jobs"
(Каталог "profile") жуть, должен быть каталог users (ты же не профили показываешь, а людей)
Стили - должны быть свои для каждого каталога отдельно, идеально даже для каждого шаблона отдельно, пока их мало - лучше прямо в шаблоне в теге <style scoped></style>
Контроллеры - отдельно для каждого каталога

**Comment by ma1405** [comment]
посижу - покумекаю...

**Comment by VintorezVS** [comment]
Сделано
