### ISSUE TITLE
Контроллеры

### ISSUE THREAD

**Issue by VintorezVS** [webwayer/skills#67]
@webwayer, можно ли сделать так, чтобы каждый контроллер не парсил для себя каждый раз skills.json (и остальные возможно)? Я думаю, будет ли работать если один раз в /front/app.js спарсить skills.json и записать результат в $rootScope (можно еще прогнать через getAllSkillsObject())?
ПС: Если нельзя так сделать, то скажи почему и закрывай тему.

**Comment by webwayer** [comment]
Можно, сделать сервис, который будет кешировать скилы и вызывать его во всех котроллерах. А сервис пусть просит их с сервера - только 1 раз, а дальше отдает то что у себя сохранил.
Можно даже пойти дальше, и держать это все в LocalStorage (но это уже только на продакшене)

**Comment by VintorezVS** [comment]
тему можно закрыть
