### ISSUE TITLE
Перевести все в material и выпилить bootstrap

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#92]

**Comment by alexeychikk** [comment]
Я думаю это задание нужно разбить на несколько (или множество) более конкретных, потому что нам нужно еще сделать что-то с "MAIN", со страницой, когда на лого нажимаешь (сейчас ведет к той же, что и "MAIN"), запилить нормальные страницы для решения, проверки, подтверждения, детального обзора и создания заданий, для просмотра своей страницы, настроек своего профиля, просмотра страницы других пользователей (может с ангуларом это будет та же страница, что и свою смотреть). Вроде все, может если еще есть че - добавьте.

**Comment by VintorezVS** [comment]
@alexeychikk, ну так разбей и проставь майлстоны, а это удали.

**Comment by alexeychikk** [comment]
@VintorezVS, cначала нужно ушатать, какие страницы будут, в чем их цель и каково наполнение, а потом уже майлстоны пилить

**Comment by alexeychikk** [comment]
Хотя в принципе большую часть майлстонов уже сейчас можно втулить, но это не важно. Ты читал вот это:
> Как мы тогда решили? Новости и обновления показываются когда на логотип нажимаешь, вместо MAIN - моя страница (что тут будет? скилы и нидсы?), а когда на никнейм жмешь - настройки профиля (какие) или как?
