### ISSUE TITLE
Страница "Моя страница" (страница для решения, проверки, подтверждения и создания задач )

### ISSUE THREAD

**Issue by webwayer** [webwayer/skills#94]

**Comment by alexeychikk** [comment]
Это вместо MAIN или это когда на никнейм нажимаешь?

**Comment by alexeychikk** [comment]
Как мы тогда решили? Новости и обновления показываются когда на логотип нажимаешь, вместо MAIN - моя страница (что тут будет? скилы, нидсы и т.д.?), а когда на никнейм жмешь - настройки профиля или как?

**Comment by alexeychikk** [comment]
У меня есть идея для основной страницы, с которой начинается взаимодействие пользователя с нашей системой (только название "Моя страница", как по мне, не отражает ее суть): на ней будут четыре раздела (над оформлением нужно подумать) со следующими заголовками и подзаголовками (все подзаголовки я предоставлю, когда каждый над ними подумает, чтобы не было зацикливания на уже имеющихся): "Решить" ("Решите предложенные задания, чтобы улучшить свои навыки и приблизиться к целям"); "Проверить" ("..."); "Подтвердить" ("..."); "Создать" ("..."). Есть идеи получше - предлагайте. Буду рад любой критике~~-нытике~~.

**Comment by VintorezVS** [comment]
@VintorezVS

Как будет выглядеть область для решения задач (если хотя бы для программирования, то это надо среду запилить...)? Я думаю надо просто, что бы пользователь загрузил файлы решения задачи (что угодно код, текст, картинки).

@webwayer

Да, среду пилить - явно не наш вариант.

@alexeychikk

Можно решения прекреплять в виде файлов, если там что-то объемное или если по другому не получится дать ответ. А если ответ короткий, но содержит код, то поддержку синтаксиса я думаю не сложно впаять, уверен готовые скрипты уже есть.

@webwayer

+1 про подсветку и файлы

**Comment by VintorezVS** [comment]
Готово
